version: "3"

services:
  cuisine-connect:
    stdin_open: true
    tty: true
    container_name: cuisine-connect
    build:
      context: .
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    #    environment:
    #      ENV_VARIABLE: ${ENV_VARIABLE}
    #      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set envrionment variables based on the .env file
    env_file:
      - ./cuisine-connect/.env.local
    volumes:
      - ./cuisine-connect:/app
    #      - ./cuisine-connect/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)
  cuisine-connect-db:
    build:
      context: .
      dockerfile: mongodb.dev.Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_REPLICA_HOST: cuisine-connect-db
      MONGO_REPLICA_PORT: "27017"
    ports:
      - 27017:27017
    networks:
      - my_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
