version: '3'

services:
  cuisine-connect:
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    env_file:
      - ./cuisine-connect/.env.local
    ports:
      - 3000:3000
    networks:
      - my_network

  cuisine-connect-db:
    build:
      context: .
      dockerfile: mongodb.dev.Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_HOST: cuisine-connect-db
      MONGO_REPLICA_PORT: "27017"
    ports:
      - 27017:27017
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true